### ISSUE TITLE
Radiation rework

### ISSUE THREAD

**Issue by gotmachine** [Kerbalism/Kerbalism4#5]
### Changes summary : 
- High energy / low energy radiation distinction : storms are high energy, other sources are low energy. Emitters are configurable.
- Any resource can be be defined as a shielding resource, with separate HVL (Half-Value Layer) definitions for low / high energy radiation.
- All parts provide some amount of shielding by default.
- Radiation occlusion is now applied to both storm radiation and local (emitters) radiation. Occlusion computations are now a lot more accurate, accounting for occluder thickness and cross-section, and for the type of resources they contain.
- Active shielding now is based on a relatively realistic concept using pairs of toroid coils that generate a capsule shaped magnetic field. Parts enclosed in the field get their radiation reduced. The coils must be charged with large amounts of EC and can also act as very large capacity batteries.  See https://github.com/Kerbalism/Kerbalism/blob/206fd5951567ba598f4a858d9eccb69696849183/misc/radiation/1000_Burger.pdf
- Radiation is now fully independent from the habitat system, and can potentially be used in a coherent way for reliability.

### Todo
- [x] Separate rules for long term / short term exposure (see further notes, and Kerbalism/Kerbalism4#4)
- [x] Some more detailed in-flight UI info (hab storm protection, radiation per source tooltip...)
- [ ] Planner support and UI
- [x] Coil fields inter-vessel effect
- [x] Inter-vessel occlusion
- [x] ModuleKsmRadiationEmitter reflection based activation
- [ ] Occlusion stats reevaluation on unloaded vessels
- [ ] Separate raytracing queue for storm radiation
- [ ] Update emitters in support configs
- [ ] Coil fields balancing
- [ ] General balance and configs

### Wishlist :
- Habitat auto-shelter system
- Some solution for volume/surface dynamic evaluation for deployable/procedural/mesh switchable parts
- Directional raycasted planetary/sun radiation
- Per part config override for IsOccluder

### Radiation rule :
There is the other side of the radiation feature : the radiation rule(s). Currently, instead of being based on realistic values, radiation source levels are orders of magnitude lower because any radiation level contribute to a non recoverable "dose accumulation". The dose at which we kill kerbals is entirely arbitrary and doesn't relate in any way to either IRL high-level exposition short-term radiation poisoning or IRL long term cancer risk, but rather an arbitrary game balance choice. 

Say you plan for a 4 years missions. Even if you design the vessel with full shielding, short and hard to plan for events of medum/high level radiation exposure will hugely increase the dose accumulation, basically bricking the mission. IRL, such events would cause short term radiation poisoning from which you can recover, and while there is an effect on long term cancer risk, there is no such thing as "you will die for sure in 2 years". Either the absorbed dose is just too high and you die short term, either you recover and loose some (and possibly a lot) years of life expectancy. There is the possibility of developing permanent conditions that will evolve badly over some time, for example radiation nephropathy causing kidney failures. But the point is that you don't develop radiation sickness symptoms due to long term exposure to low-moderate radiation exposure.

Aside from that issue, since configured radiation source levels are way too low compared to reality and the new occlusion / shielding mechanics use relatively realistic formulas, they are orders of magnitude too effective.

Trying to balance everything against an arbitrary rule that is conceptually wrong is a bad idea.
So, regardless of what is done for Kerbalism/Kerbalism4#4, the solution is to implement two separate rules :
- Short term effect of medium/high level exposure.
- Long term risk of overall lifetime exposure.

Basically, the idea is to have the first rule being triggered only when radiation is above a threshold and being restored under that threshold, while the second rule is always active and never recovered from. Some scaling functions on the exposure are likely needed instead of a hard threshold, but the concept stays the same.

Some wikipedia based documentation :
- ACS (Acute radiation syndrome) - https://en.wikipedia.org/wiki/Acute_radiation_syndrome :
  - Caused by short term exposure > ~10 rad/h.
  - Death or recovery in 1 day to 6 weeks
  - Highly deterministic (duration and mortality rate proportional to the exposure)
- CRS (Chronic radiation syndrome) - https://en.wikipedia.org/wiki/Chronic_radiation_syndrome
  - Caused by short/medium term exposure > ~0.001 rad/h and totaling more than 110±40 rad
  - Various permanent health conditions degrading slowly over several years
  - Highly deterministic (apparition, evolution and severity of symptoms proportional to the exposure)
- Radiation-induced cancer - https://en.wikipedia.org/wiki/Radiation-induced_cancer
  - Probabilistic : higher lifetime accumulated dose increase the *chance* to develop a cancer.
  - Probability increased by any non zero exposure level (no "safe" threshold)
  - Mortality rate of the cancer is fully independent from the exposure level (a higher dose doesn't give you a worse cancer)
  - It's very hard to find probability figures (because there are a lot of factors, and because the science isn't very solid), but :
    - A baseline average for lifetime fatal radiation induced cancer can be something like 0.01-0.05% / rad
    - NASA baseline gives 3% probability for a ~70 rad dose absorbed over a year at age 30-40 (page 117 : https://spaceradiation.jsc.nasa.gov/irModels/TP-2013-217375.pdf) 

### Solar storms

Regarding solar storms, maybe we should revisit the balance. IMO, they happen way too often and are annoying to manage.
In the context of a possible implementation of crew radiation shelters, it would be more interesting to have less frequent but longer duration storms
Also, the default duration of 2 hours is likely to cause a dose overestimation at high timewarp rates.
So I would suggest to make the storms less frequent but possibly more deadly, and to make them last way longer (a few days)

Another thing would be to make storms star-system wide, which is arguably a bit less realistic but would prevent being spammed all the time when you have vessels everywhere.

Or we could be a bit fancier and generate storms with a random direction and relatively large cone angle, and apply it's effect to everything within the cone angle.

Having less events, but events that happen simultaneously would cut on timewarp stopping annoyance when you have a lot of vessels in flight, and incentive the player to actually "play" the event instead of being annoyed and just disabling the notification.

#### Summary of radiation sources :
- GCR aka "cosmic radiation". Very high energy particules that have a high penetration and cause high levels of secondary radiation when they hit something. Can be considered omnidirectional. "Counteracted" by the solar wind, and consequently inversely proportional to the solar activity min/max. Further counteracted by bodies magnetic fields and atmosphere.
- "Normal" solar wind/flares : low energy / medium level particules and radiation. Directional. Counteracted by bodies magnetic fields and atmosphere.
- "Exceptional" solar wind aka "solar storm" : high energy/ high level particules. Counteracted by bodies magnetic fields and atmosphere, but high energy ones have complex secondary effects and interactions with bodies magnetic fields and atmospheres. Directional, but secondary effects might not. "medum intensity" events are significant in interplanetary space, but have little to no effects in the vicinity of bodies that have strong magnetic fields. Frequency/intensity proportional to solar cycle
- Radiation belts : low-medium energy/level. Essentially near-bodies regions where GCR/solar wind particules are being "trapped" by a body magnetic field. Omnidirectional while you are inside them.
- Local radiation emitters : RTGs (altough most of them are negligible unless you sleep against one every night), nuclear reactors/engines, etc...

We have a handful of config-defined base radiation rates that would need to be checked :
- Bodies `radiation_surface` : emitted by bodies toward all visible vessels. Sun, Jool, Vall... Check the assumption that for solar wind : "we want ~0.01 rad/h at Kerbin (d = 1 AU)"
- Bodies `radiation_pause` : negative value representing the magnetosphere protection against solar wind / events.
- Solar storm radiation

Some data points : 

#### https://arxiv.org/ftp/arxiv/papers/1805/1805.01643.pdf

- At 4mm aluminum shielding, outside the Earth belts in 1969 (solar min/max ?) : 0.02 to 0.4 rad/h

| Aluminium shielding   (mm) | Apollo dose (rad) | rad/h    |
|----------------------------|-------------------|----------|
| 0,2                        | 410               | 2,277778 |
| 1                          | 83,5              | 0,463889 |
| 4                          | 3,96              | 0,022000 |
| 7                          | 0,21              | 0,001167 |
| > 14                       | 0,01              | 0,000056 |

Total dose with 7 mm alu shielding :
| Solar cycle state                       | max (rad) | max (rad/h) | min (rad) | min (rad/h) |
|-----------------------------------------|-----------|-------------|-----------|-------------|
| Van Allen belt passage (2 h)            | 0,2       | 0,10500     | 0,2       | 0,10500     |
| Journey to the Moon and back (7,5 days) | 36,1      | 0,20056     | 0,0       | 0,00000     |
| 2 h on the lunar surface                | 4,3       | 2,15000     | 0,0       | 0,00000     |
| Journey to Mars (one way, 8 months)     | 1155,2    | 0,20056     | 9,5       | 0,00165     |

#### https://www.nature.com/articles/s41526-018-0043-2 :
- October 1989 large solar storm (SPE) : 145,4 rad/h with 5 g/cm2 shielding in interplanetary space (Apollo : 6.15 g/cm2)
- GCR in interplanetary space :  5–10 rad/year at solar maximum to 15–30 rad/year at solar minimum
- GCR reduction by 20–30 g/cm2 aluminum shielding : 25%
- GCR reduction by 20–30 g/cm2 polyethylene shielding : 35%

#### ExoMars : http://space.bas.bg/SES/archive/SES%202020_DOKLADI/1_Space%20Physics/1_Semkova.pdf
GCR radiation behind 20 g/cm² aluminum shielding, end of 2018 - solar minimum
- GCR in "free space" at 1.5 AU : 0.00175 rad/h
- GCR in mars orbit : 0.00145 rad/h

#### MSL-RAD : https://sci-hub.se/10.1093/rpd/ncv297
GCR and SPE radiation during earth-mars transit, 2011-2012, solar maximum. No shielding ?
- 0.00195 rad/h from GCR
- 5 significant (ie, larger than the average GCR effect) SPE events over 7 months, totaling 2.47 rad

Radiation on mars surface (omnidirectional : scattered by the atmosphere and the soil)
- 0.000875 rad/h

#### Radiation in the earth radiation belts at 2 different altitudes, as a function of aluminium shielding thickness
![image](https://user-images.githubusercontent.com/24925209/133680209-e3aabb46-673e-4967-927d-6b85298d56a9.png)

#### Quick bibliography :
- [Good (detailed) summary about GCR, solar wind, solar storms and radiation belts](http://sirad.pd.infn.it/~candelor/Parte1/Parte1_01_TNS2008_NearEarthSpaceRadiationEnvironment%28Radecs2007%29_OKPerCorso.pdf)
- [Radiation rates in moon orbit, mainly for GCR, but some data about SPE too](https://agupubs.onlinelibrary.wiley.com/doi/full/10.1029/2011JE003978)

![image](https://user-images.githubusercontent.com/24925209/133822826-ef0606aa-3443-4e55-9191-4057036a10ee.png)

### Undecided/Postponed :

**Processes**
Do we need a process controller that can emit radiation depending on the process state ? Currently we have no real use for that if we put aside other mods EC generating nuclear reactors, which are due for a special treatment anyway. If we do it, maybe it would be better to implement module-linking in a single ModuleKsmRadiationEmitter per part instead of implementing IRadiationEmitter on ProcessControllers : 
- That would bloat the emitter cache for no good reason, leading to a lot of useless checks.
- Having multiple emitters modules on the same part would lead to redundant raycasts,

**Active shielding**
The current implementation simply reduce all radiation sources for every part enclosed in the capsule shaped eletromagnetic field.
This works and is simple to understand from the player POV. 
This said, the RL way this works is by generating a cylindrical shaped field, that offer no protection from incoming radiation along the cylinder axis. This could be implemented as a raycastable cylindrical occluder. However this would make the shields significantly harder to use as you would have to orient it according to the direction of the radiation sources. And we would still need to treat them as an "enclosing" shield for ambiant (non-directional) radiation from belts and bodies in some way, which would probably lead to even more confusion. It would also be impossible to compute consistent results if the player design the "radiation protected" area with an active shield and some passive occluders (tanks...) to fill the cylindrical field open caps.
